services:
  - type: web
    name: portfolio
    env: static
    buildCommand: npm install --production=false --legacy-peer-deps && next build && next export
    staticPublishPath: ./out
    # Redirects for SPA
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
    plan: free
    buildFilter:
      paths:
        - app/**
        - components/**
        - lib/**
        - public/**
        - hooks/**
        - styles/**
        - package.json
        - next.config.mjs
